<?php
/**
 * Sibling detection: Visibility (native-aeo-pack).
 *
 * VigIA and Visibility are siblings in the AyudaWP family with a deliberate
 * split of responsibilities by NATURE, not by topic: Visibility OWNS the
 * emission of AI/search signals (Site Identity schema, llms.txt / llms-full.txt,
 * Markdown for agents, the robots.txt editor for AI), while VigIA OWNS
 * observation and control (crawler analytics, stats, hard PHP/403 blocking,
 * email alerts, the control MCP server).
 *
 * From Visibility 1.7.0 the emission lives in Visibility, reusing VigIA's code.
 * The coordination is unidirectional: Visibility takes priority and never defers
 * to VigIA; VigIA is the one that detects Visibility and yields a signal when
 * (and only when) Visibility is actively emitting that specific signal. If
 * Visibility is active but a given signal is turned off there, VigIA keeps
 * emitting it, so a signal is never dropped by both at once ("someone always
 * emits", Visibility first).
 *
 * Integration contract (Visibility 1.7.0), all read here without a hard
 * dependency on the sibling's classes:
 *   - Presence:  constant NATIVE_AEO_PACK_VERSION.
 *   - Settings:  option `native_aeo_pack_settings`, grouped by module, read via
 *                Native_AEO_Pack_Settings::get() / ::is_module_enabled() when the
 *                class is loaded (it loads before VigIA in alphabetical plugin
 *                order), with a raw-option fallback that mirrors its defaults.
 *   - Identity:  module `meta_tags` on AND meta_tags.schema_identity = true.
 *   - llms:      meta_tags.llms_enabled (+ llms_full_enabled for the -full file).
 *   - markdown:  meta_tags.markdown_enabled.
 *   - robots AI: Visibility's robots.txt-for-AI editor loads under the
 *                `meta_tags` module (it moved to the Discover tab in 1.7.0), but
 *                its keys stay in the `noindex` group. So: `meta_tags` module on
 *                AND ( noindex.robots_block_ai OR a non-empty noindex.robots_custom ).
 *                `robots_physical` is a delivery toggle, not content, so it does
 *                not by itself mean Visibility is emitting robots rules.
 *   - File markers Visibility writes (so VigIA can recognise and clean them):
 *                llms.txt   -> first line begins with "# Generated by Visibility".
 *                robots.txt -> block between "# BEGIN Visibility" and "# END Visibility".
 *
 * @package VigIA
 * @since 2.3.0
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Detector and cession gate for the Visibility sibling plugin.
 */
class VigIA_Sibling_Visibility {

	/**
	 * Visibility's single settings option.
	 */
	const SIBLING_OPTION = 'native_aeo_pack_settings';

	/**
	 * Header Visibility writes at the top of a physical llms.txt / llms-full.txt.
	 * Matched as a prefix (the real line carries a trailing explanatory note).
	 */
	const LLMS_MARKER = '# Generated by Visibility';

	/**
	 * BEGIN/END markers wrapping Visibility's block inside a physical robots.txt.
	 */
	const ROBOTS_MARK_BEGIN = '# BEGIN Visibility';
	const ROBOTS_MARK_END   = '# END Visibility';

	/**
	 * Top-level modules that default to enabled in Visibility, for the raw-option
	 * fallback (when the sibling's settings class is not loaded). Mirrors
	 * Native_AEO_Pack_Settings::defaults()['modules'].
	 *
	 * @var array<int,string>
	 */
	private static $sibling_default_modules = array( 'meta_tags', 'noindex', 'sitemap', 'redirects' );

	/**
	 * Is the Visibility sibling present and loaded?
	 *
	 * Uses the version constant rather than is_plugin_active() so the check works
	 * on the frontend too (is_plugin_active() lives in wp-admin and is not loaded
	 * during wp_head / template_redirect, where the emitters run).
	 *
	 * @return bool
	 */
	public static function is_active() {
		return defined( 'NATIVE_AEO_PACK_VERSION' );
	}

	/**
	 * Public display name for the sibling, for notices.
	 *
	 * @return string
	 */
	public static function name() {
		return 'Visibility';
	}

	/**
	 * Read a single Visibility setting from a module group.
	 *
	 * Prefers the sibling's own accessor (which applies its defaults) and falls
	 * back to reading the raw option so VigIA never fatals if the class signature
	 * changes or the class is not yet loaded.
	 *
	 * @param string $group   Module group (meta_tags, noindex, sitemap, modules).
	 * @param string $key     Key inside the group.
	 * @param mixed  $default Returned when the key is absent.
	 * @return mixed
	 */
	public static function setting( $group, $key, $default = null ) {
		if ( class_exists( 'Native_AEO_Pack_Settings' ) ) {
			return Native_AEO_Pack_Settings::get( $group, $key, $default );
		}

		$option = get_option( self::SIBLING_OPTION, array() );
		if ( is_array( $option ) && isset( $option[ $group ] ) && is_array( $option[ $group ] ) && array_key_exists( $key, $option[ $group ] ) ) {
			return $option[ $group ][ $key ];
		}

		return $default;
	}

	/**
	 * Is a top-level Visibility module enabled?
	 *
	 * @param string $module Module key (meta_tags, noindex, sitemap).
	 * @return bool
	 */
	public static function module_enabled( $module ) {
		if ( class_exists( 'Native_AEO_Pack_Settings' ) ) {
			return Native_AEO_Pack_Settings::is_module_enabled( $module );
		}

		$option = get_option( self::SIBLING_OPTION, array() );
		if ( is_array( $option ) && isset( $option['modules'][ $module ] ) ) {
			return ! empty( $option['modules'][ $module ] );
		}

		// Absent key: fall back to Visibility's own default for that module.
		return in_array( $module, self::$sibling_default_modules, true );
	}

	/**
	 * Is Visibility emitting the Site Identity schema (Organization/Person + WebSite)?
	 *
	 * @return bool
	 */
	public static function emits_identity() {
		return self::is_active()
			&& self::module_enabled( 'meta_tags' )
			&& (bool) self::setting( 'meta_tags', 'schema_identity', false );
	}

	/**
	 * Is Visibility serving llms.txt?
	 *
	 * @return bool
	 */
	public static function emits_llms() {
		return self::is_active()
			&& self::module_enabled( 'meta_tags' )
			&& (bool) self::setting( 'meta_tags', 'llms_enabled', false );
	}

	/**
	 * Is Visibility serving llms-full.txt?
	 *
	 * @return bool
	 */
	public static function emits_llms_full() {
		return self::emits_llms()
			&& (bool) self::setting( 'meta_tags', 'llms_full_enabled', false );
	}

	/**
	 * Is Visibility serving Markdown for agents (/{slug}.md)?
	 *
	 * @return bool
	 */
	public static function emits_markdown() {
		return self::is_active()
			&& self::module_enabled( 'meta_tags' )
			&& (bool) self::setting( 'meta_tags', 'markdown_enabled', false );
	}

	/**
	 * Is Visibility actually emitting robots.txt directives for AI crawlers?
	 *
	 * Mirrors Visibility 1.7.0's own emission condition. Its robots-for-AI editor
	 * (`Native_AEO_Pack_Robots_Txt`) is registered only when the `meta_tags`
	 * module is on (the editor lives in the Discover tab), and its `build()`
	 * outputs a block only when the AI-block toggle is on or custom lines are set.
	 * The settings keys themselves still live in the `noindex` group. The
	 * physical-file toggle is delivery only, so it is NOT a content trigger:
	 * counting it would make VigIA cede into a void when Visibility emits nothing.
	 *
	 * @return bool
	 */
	public static function emits_robots_ai() {
		if ( ! self::is_active() || ! self::module_enabled( 'meta_tags' ) ) {
			return false;
		}

		$block_ai = (bool) self::setting( 'noindex', 'robots_block_ai', false );
		$custom   = trim( (string) self::setting( 'noindex', 'robots_custom', '' ) );

		return $block_ai || '' !== $custom;
	}

	/**
	 * Should VigIA yield a given emission signal to Visibility?
	 *
	 * True only when Visibility is actively emitting that signal. The
	 * `vigia_defer_emission_to_visibility` filter (default true) is the escape
	 * hatch for sites that prefer to keep VigIA's own emission even with
	 * Visibility active: returning false there forces VigIA to keep emitting.
	 *
	 * @param string $signal One of: identity, llms, llms_full, markdown, robots.
	 * @return bool
	 */
	public static function should_defer( $signal ) {
		switch ( $signal ) {
			case 'identity':
				$emits = self::emits_identity();
				break;
			case 'llms':
				$emits = self::emits_llms();
				break;
			case 'llms_full':
				$emits = self::emits_llms_full();
				break;
			case 'markdown':
				$emits = self::emits_markdown();
				break;
			case 'robots':
				$emits = self::emits_robots_ai();
				break;
			default:
				$emits = false;
				break;
		}

		if ( ! $emits ) {
			return false;
		}

		/**
		 * Filter whether VigIA defers an emission signal to the Visibility sibling.
		 *
		 * Only fires when Visibility is actually emitting the signal. Return false
		 * to keep VigIA emitting it anyway (the "I prefer VigIA's emission" camp).
		 *
		 * @since 2.3.0
		 *
		 * @param bool   $defer  Whether to defer to Visibility. Default true.
		 * @param string $signal The signal: identity, llms, llms_full, markdown, robots.
		 */
		return (bool) apply_filters( 'vigia_defer_emission_to_visibility', true, $signal );
	}
}
